#!/bin/bash

# KILL EXISTING PROCESSES
killall swaybg
killall gBar

# STARTUP PROCESSES
swaybg -i ~/walls/dreamy/$(\ls ~/walls/dreamy | shuf -n 1) &
gBar bar 0 &
# rclone --vfs-cache-mode writes mount "OneDrive": ~/OneDrive &

riverctl spawn "dbus-update-activation-environment SEATD_SOCK DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river" &

# VARIABLE DEFINITIONS
APPDEF_FILEMAN=nautilus
APPDEF_TERM="kitty -e"
# APPDEF_EDIT="$APPDEF_TERM -e nvim"
APPDEF_BROWSER=brave

# KEYBINDINGS
riverctl map normal Super Return  spawn "$APPDEF_TERM" &
riverctl map normal Super F       spawn "$APPDEF_BROWSER" &
riverctl map normal Super C       spawn "$APPDEF_EDIT" &
riverctl map normal Super+Shift S spawn 'grim -g "$(slurp)" - | wl-copy' &

riverctl map normal Super D       spawn "rofi -show drun" &
riverctl map normal Super R       spawn "rofi -show run" &
riverctl map normal Super+Shift E spawn "~/.config/rofi/scripts/powermenu.sh" &
riverctl map normal Super M       spawn "~/.config/rofi/scripts/spotify.sh" &
riverctl map normal Super G       spawn "~/.config/rofi/scripts/translate.sh" &
riverctl map normal Super A       spawn 'xdg-open $(locate / | rofi -threads 0 -dmenu -i -p "locate:")' &

for mode in normal locked
do

	riverctl map $mode None XF86AudioRaiseVolume spawn 'pamixer -i 5 && notify-send -e "Volume Control" "$(pamixer --get-volume-human)" -r 999' &
	riverctl map $mode None XF86AudioLowerVolume spawn 'pamixer -d 5 && notify-send -e "Volume Control" "$(pamixer --get-volume-human)" -r 999' &
	riverctl map $mode None XF86AudioMute spawn "pamixer --toggle-mute" &
	riverctl map $mode None XF86AudioPause spawn "pamixer play-pause" &
	riverctl map $mode None XF86AudioNext spawn "playerctl next" &
	riverctl map $mode None XF86AudioPrevious spawn "playerctl previous" &

done

# RIVER KEYBINDINGS
riverctl map normal Super Q close

riverctl map normal Super J focus-view next &
riverctl map normal Super H focus-view next &
riverctl map normal Super L focus-view previous &
riverctl map normal Super K focus-view previous &

riverctl map normal Super+Shift J swap next &
riverctl map normal Super+Shift H swap next &
riverctl map normal Super+Shift L swap previous &
riverctl map normal Super+Shift K swap previous &

riverctl map normal Super+Control H send-layout-cmd rivertile "main-ratio -0.02"
riverctl map normal Super+Control L send-layout-cmd rivertile "main-ratio +0.02"

riverctl map-pointer normal Super BTN_LEFT move-view &
riverctl map-pointer normal Super BTN_RIGHT resize-view &

for i in $(seq 1 9); do
	tags=$((1 << ($i -1)))
	riverctl map normal Super $i set-focused-tags $tags
    riverctl map normal Super+Shift $i set-view-tags $tags
done

riverctl map normal Super Space toggle-float &
riverctl map normal Super S toggle-fullscreen &
riverctl map normal Super+Shift R spawn "~/.config/river/init"

riverctl map normal None XF86MonBrightnessUp   spawn 'brightnessctl -d intel_backlight s +5%'
riverctl map normal None XF86MonBrightnessDown spawn 'brightnessctl -d intel_backlight s 5%-'

riverctl set-repeat 35 300

riverctl border-color-focused   0xf5c2e7
riverctl border-color-unfocused 0x45475a

riverctl default-layout rivertile
rivertile -view-padding 2 -outer-padding 2 -main-ratio 0.50 &
