#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d www dev doc ent misc virt etc 8 9 10

bspc config border_width        04
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

sxhkd &
spotifyd
polybar &
picom -b --animations --animation-window-mass 0.5 --animation-for-open-window zoom --animation-stiffness 350 &
xrandr -r 144
/home/dt/.walls.sh
shutter --min_at_startup
rclone --vfs-cache-mode writes mount "OneDrive": ~/OneDrive
