#!/usr/bin/env bash

## Author  : Aditya Shakya
## Mail    : adi1090x@gmail.com
## Github  : @adi1090x
## Twitter : @adi1090x
dir="$HOME/.config/rofi/powermenu/type-2"
rofi_command="rofi -theme $dir/style-2.rasi"

uptime=$(uptime -p | sed -e 's/up //g')

## Options
shutdown=""
reboot=""
lock=""
logout=""

## Message
msg() {
    rofi -theme "$dir/message.rasi" -e "Available Options  -  yes / y / no / n"
}

## Variable passed to rofi
options="$shutdown\n$reboot\n$lock\n$logout"

chosen="$(echo -e "$options" | $rofi_command -p "Uptime: $uptime" -dmenu -selected-row 2)"
case $chosen in
    $shutdown)
        systemctl poweroff
        ;;
    $reboot)
        systemctl reboot
        ;;
    $lock)
        swaylock
        ;;
    $logout)
        killall Hyprland
        ;;
esac
