#!/bin/sh

getDefaultSink() {
    defaultSink=$(pactl info | awk -F : '/Default Sink:/{print $2}')
    description=$(pactl list sinks | sed -n "/${defaultSink}/,/Description/s/^\s*Description: \(.*\)/\1/p")
    echo "${description}"
}

getDefaultSource() {
    defaultSource=$(pactl info | awk -F : '/Default Source:/{print $2}')
    description=$(pactl list sources | sed -n "/${defaultSource}/,/Description/s/^\s*Description: \(.*\)/\1/p")
    echo "${description}"
}

ALLICONS=("奄" "奔" "墳")

VOLUME=$(pamixer --get-volume-human)
SINK=$(getDefaultSink)
SOURCE=$(getDefaultSource)
VOLICON=${ALLICONS[3 * ${VOLUME::-1}/100]}
if [ ${VOLUME::-1} == 100 ]
  then
    VOLICON=${ALLICONS[2]}
  elif [ $VOLUME == "muted" ]
  then
    VOLICON="🔇"
fi

case $1 in
    "--up")
        pamixer --increase 10
        ;;
    "--down")
        pamixer --decrease 10
        ;;
    "--mute")
        pamixer --toggle-mute
        ;;
    *)
        echo $VOLICON ${VOLUME} #echo "Source: ${SOURCE} | Sink: ${VOLUME} ${SINK}" 
esac
