theme ="catppuccin_macchiato"

[editor]
line-number = "relative"
bufferline = "multiple"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.space]
s = ":write-all"
e = ":wq"

[keys.insert]
C-s = ["normal_mode", "move_char_right", "insert_mode"]

[editor.cursor-shape]
insert = "bar"
